baseURL = 'https://codigrowa.batako.net/'
languageCode = 'ja-jp'
title = 'Codigrowa Docs'
defaultContentLanguage = 'ja'
theme = 'book'
enableRobotsTXT = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookSearch = true
  BookRepo = 'https://github.com/BatakoStudio/codigrowa'
  BookEditPath = 'tree/main'
